spring.application.name=bootiful
#
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true
#
spring.security.user.name=simon
spring.security.user.password=pw
#
#export SPRING_AI_OPENAI_API_KEY=..
#
spring.mvc.apiversion.default=1.1
spring.mvc.apiversion.use.header=x-dogs-version
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret